project:
  type: website

website:
  title: "Jacqueline Ferri -  Portfolio"
  navbar:
    title: "Jacqueline Ferri"
    left:
      - text: Home
        href: index.qmd
      - text: About
        href: about.qmd
      - text: Example analysis
        href: example_analysis.qmd
    
format:
  html:
    theme: pulse
    toc: true
    css: styles.css

output-dir: docs

